---
# tasks for kibana
- name: update repositories cache and install kibana package
  ansible.builtin.apt:
    name: kibana
    update_cache: yes

- name: copy kibana configuration
  ansible.builtin.template:
    src: kibana.yaml.j2
    dest: "{{ kibana_conf_dir }}/{{ kibana_config_file }}"
    owner: root
    group: kibana
    mode: 0660
  notify: reload_daemon_restart_kibana

- name: force restart
  meta: flush_handlers

- name: start service kibana
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: true